# Generated by Django 2.1.3 on 2018-11-18 06:05

from django.db import migrations, models
import django.db.models.deletion
import simditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner/%Y/%m')),
                ('url', models.URLField()),
                ('index', models.IntegerField(default=100)),
                ('is_show', models.IntegerField(choices=[(1, '显示'), (0, '不显示')], default=0)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Blogroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=15)),
                ('website_link', models.URLField()),
                ('remark', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Blogroll',
                'verbose_name_plural': 'Blogroll',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=300)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('zh_name', models.CharField(max_length=20)),
                ('en_name', models.CharField(max_length=20)),
                ('icon', models.ImageField(upload_to='icon/%Y/%m')),
                ('star', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=3)),
                ('website', models.URLField(blank=True, null=True)),
                ('platform', models.CharField(max_length=15)),
                ('tags', models.CharField(max_length=15)),
                ('contract_address', models.URLField(blank=True, null=True)),
                ('short_description', models.CharField(max_length=30)),
                ('parti_description', simditor.fields.RichTextField()),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game Detail',
                'verbose_name_plural': 'Game Detail',
            },
        ),
        migrations.CreateModel(
            name='GameSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_wechat', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_qq', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('official_wechat', models.CharField(blank=True, max_length=20, null=True)),
                ('official_weibo', models.URLField(blank=True, null=True)),
                ('official_facebook', models.URLField(blank=True, null=True)),
                ('official_twitter', models.URLField(blank=True, null=True)),
                ('official_telegram', models.URLField(blank=True, null=True)),
                ('zh_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameDetail')),
            ],
            options={
                'verbose_name': 'Sccial Contact',
                'verbose_name_plural': 'Sccial Contact',
            },
        ),
        migrations.CreateModel(
            name='GameView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_number', models.PositiveIntegerField(default=0)),
                ('like_number', models.PositiveIntegerField(default=0)),
                ('zh_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameDetail')),
            ],
            options={
                'verbose_name': 'Web Analytics',
                'verbose_name_plural': 'Web Analytics',
            },
        ),
    ]
