# Generated by Django 2.1.3 on 2018-11-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameview',
            name='zh_name',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='view_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GameView',
        ),
    ]
