# Generated by Django 2.1.3 on 2018-12-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bannerL/%Y/%m')),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=100)),
                ('is_show', models.IntegerField(choices=[(1, '显示'), (0, '不显示')], default=0)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner(L)',
                'verbose_name_plural': 'Banner(L)',
            },
        ),
        migrations.CreateModel(
            name='BannerS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bannerS/%Y/%m')),
                ('url', models.URLField()),
                ('order', models.IntegerField(default=100)),
                ('is_show', models.IntegerField(choices=[(1, '显示'), (0, '不显示')], default=0)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner(S)',
                'verbose_name_plural': 'Banner(S)',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='gameview',
            name='zh_name',
        ),
        migrations.RenameField(
            model_name='blogroll',
            old_name='website_link',
            new_name='website_url',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='like_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='show_name',
            field=models.CharField(default='poketmon', max_length=20),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='slug',
            field=models.SlugField(default='cat', editable=False),
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='view_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='en_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='short_description',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='tags',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='zh_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='GameView',
        ),
    ]
