# Generated by Django 2.1.3 on 2018-11-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181129_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedetail',
            name='slug_name',
            field=models.SlugField(default='any_name', editable=False),
        ),
    ]
