# Generated by Django 2.1.3 on 2018-12-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20181210_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Game Tag',
                'verbose_name_plural': 'Game Tag',
            },
        ),
        migrations.RemoveField(
            model_name='gamedetail',
            name='tags',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='tags',
            field=models.ManyToManyField(to='game.GameTag'),
        ),
    ]
