# Generated by Django 2.1.3 on 2018-12-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamedetail_slug_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedetail',
            name='slug_name',
        ),
        migrations.AddField(
            model_name='gamedetail',
            name='slug',
            field=models.SlugField(default='cat', editable=False),
        ),
    ]
