# Generated by Django 2.1.3 on 2018-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20181206_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bannerL/%Y/%m')),
                ('url', models.URLField()),
                ('index', models.IntegerField(default=100)),
                ('is_show', models.IntegerField(choices=[(1, '显示'), (0, '不显示')], default=0)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner(L)',
                'verbose_name_plural': 'Banner(L)',
            },
        ),
        migrations.CreateModel(
            name='BannerS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='bannerS/%Y/%m')),
                ('url', models.URLField()),
                ('index', models.IntegerField(default=100)),
                ('is_show', models.IntegerField(choices=[(1, '显示'), (0, '不显示')], default=0)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner(S)',
                'verbose_name_plural': 'Banner(S)',
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
