# Generated by Django 2.1.3 on 2018-12-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20181208_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerl',
            old_name='index',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='banners',
            old_name='index',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='show_name',
            field=models.CharField(default='poketmon', max_length=20),
        ),
    ]
