# Generated by Django 2.1.3 on 2018-12-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20181209_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogroll',
            old_name='website_link',
            new_name='website_url',
        ),
        migrations.AlterField(
            model_name='gamedetail',
            name='short_description',
            field=models.CharField(max_length=33),
        ),
    ]
